apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rrbanda/platform-components.git
    path: argocd/platform-applications
    targetRevision: main
    helm:
      parameters:
        - name: clusterRouterDomain
          value: apps.cluster-xxxxx.dynamic.redhatworkshops.io
        - name: gitHost
          value: https://github.com
        - name: gitOrg
          value: contract-first-idp
        - name: gitRef
          value: main
        - name: gitToken
          value: ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        - name: eclipseClientId
          value: xxxxxxxxxxxxxxxxxxxx
        - name: eclipseClientSecret
          value: FF00000000000000000000000000000000000000
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true       
    retry:
      limit: 10 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
